dist: trusty
language: ruby
env:
  global:
    - JRUBY_OPTS=--debug
rvm:
  - jruby-18mode
  - jruby-1.7.26
  - jruby-9.1.7.0
  - jruby-head
before_install:
  - gem update --system
branches:
  only:
    - master
