dist: trusty
language: ruby
env:
  global:
    - JRUBY_OPTS=--debug
rvm:
  - jruby-18mode
  - jruby-1.7.27
  - jruby-9.1.13.0
  - jruby-head
before_install:
  - gem install bundler
branches:
  only:
    - master
